# Generated by Django 4.0.2 on 2022-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='experts/')),
                ('social_fb', models.URLField(blank=True, null=True)),
                ('social_github', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
