# Generated by Django 4.0.2 on 2022-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xit', '0005_award_partner_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image_hover',
            field=models.ImageField(blank=True, upload_to='partner/'),
        ),
    ]
