# Generated by Django 4.0.2 on 2022-02-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xit', '0007_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
