# Generated by Django 4.0.2 on 2022-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xit', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='services',
            field=models.TextField(default=12.08),
            preserve_default=False,
        ),
    ]
