# Generated by Django 4.0.2 on 2022-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xit', '0010_contact_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
